/**
 * SEED-128 (ECB, zero-padded, lowercase hex) — a faithful JavaScript port of the
 * SEED128.java reference implementation distributed by 우정사업본부 with the
 * EMS/K-Packet OpenAPI kit.
 *
 * WHY A PORT AND NOT A LIBRARY:
 * This implementation does NOT agree with the RFC 4269 test vectors. Feeding it
 * key=00..0f / plaintext=00..0f yields a6e8d7325bbe0998cf235c1b57e64360, where
 * RFC 4269 specifies 5ebac6e0054e166819aff1cc6d346cdb — the vendor code applies a
 * different word/byte ordering. A stock SEED library would therefore produce
 * ciphertext the post office cannot decrypt. The tables and round functions below
 * were extracted directly from the vendor's Java source, and the test suite pins
 * the output against vectors generated by running that Java code.
 *
 * Also note ECB with zero padding is weak by modern standards (identical plaintext
 * blocks map to identical ciphertext blocks, and trailing NULs are ambiguous). That
 * is the protocol epost specifies; we match it rather than improve on it.
 *
 * Generated tables: do not hand-edit.
 */

const SS0 = new Int32Array([
  0x2989a1a8|0, 0x05858184|0, 0x16c6d2d4|0, 0x13c3d3d0|0, 0x14445054|0, 0x1d0d111c|0, 0x2c8ca0ac|0, 0x25052124|0,
  0x1d4d515c|0, 0x03434340|0, 0x18081018|0, 0x1e0e121c|0, 0x11415150|0, 0x3cccf0fc|0, 0x0acac2c8|0, 0x23436360|0,
  0x28082028|0, 0x04444044|0, 0x20002020|0, 0x1d8d919c|0, 0x20c0e0e0|0, 0x22c2e2e0|0, 0x08c8c0c8|0, 0x17071314|0,
  0x2585a1a4|0, 0x0f8f838c|0, 0x03030300|0, 0x3b4b7378|0, 0x3b8bb3b8|0, 0x13031310|0, 0x12c2d2d0|0, 0x2ecee2ec|0,
  0x30407070|0, 0x0c8c808c|0, 0x3f0f333c|0, 0x2888a0a8|0, 0x32023230|0, 0x1dcdd1dc|0, 0x36c6f2f4|0, 0x34447074|0,
  0x2ccce0ec|0, 0x15859194|0, 0x0b0b0308|0, 0x17475354|0, 0x1c4c505c|0, 0x1b4b5358|0, 0x3d8db1bc|0, 0x01010100|0,
  0x24042024|0, 0x1c0c101c|0, 0x33437370|0, 0x18889098|0, 0x10001010|0, 0x0cccc0cc|0, 0x32c2f2f0|0, 0x19c9d1d8|0,
  0x2c0c202c|0, 0x27c7e3e4|0, 0x32427270|0, 0x03838380|0, 0x1b8b9398|0, 0x11c1d1d0|0, 0x06868284|0, 0x09c9c1c8|0,
  0x20406060|0, 0x10405050|0, 0x2383a3a0|0, 0x2bcbe3e8|0, 0x0d0d010c|0, 0x3686b2b4|0, 0x1e8e929c|0, 0x0f4f434c|0,
  0x3787b3b4|0, 0x1a4a5258|0, 0x06c6c2c4|0, 0x38487078|0, 0x2686a2a4|0, 0x12021210|0, 0x2f8fa3ac|0, 0x15c5d1d4|0,
  0x21416160|0, 0x03c3c3c0|0, 0x3484b0b4|0, 0x01414140|0, 0x12425250|0, 0x3d4d717c|0, 0x0d8d818c|0, 0x08080008|0,
  0x1f0f131c|0, 0x19899198|0, 0x00000000|0, 0x19091118|0, 0x04040004|0, 0x13435350|0, 0x37c7f3f4|0, 0x21c1e1e0|0,
  0x3dcdf1fc|0, 0x36467274|0, 0x2f0f232c|0, 0x27072324|0, 0x3080b0b0|0, 0x0b8b8388|0, 0x0e0e020c|0, 0x2b8ba3a8|0,
  0x2282a2a0|0, 0x2e4e626c|0, 0x13839390|0, 0x0d4d414c|0, 0x29496168|0, 0x3c4c707c|0, 0x09090108|0, 0x0a0a0208|0,
  0x3f8fb3bc|0, 0x2fcfe3ec|0, 0x33c3f3f0|0, 0x05c5c1c4|0, 0x07878384|0, 0x14041014|0, 0x3ecef2fc|0, 0x24446064|0,
  0x1eced2dc|0, 0x2e0e222c|0, 0x0b4b4348|0, 0x1a0a1218|0, 0x06060204|0, 0x21012120|0, 0x2b4b6368|0, 0x26466264|0,
  0x02020200|0, 0x35c5f1f4|0, 0x12829290|0, 0x0a8a8288|0, 0x0c0c000c|0, 0x3383b3b0|0, 0x3e4e727c|0, 0x10c0d0d0|0,
  0x3a4a7278|0, 0x07474344|0, 0x16869294|0, 0x25c5e1e4|0, 0x26062224|0, 0x00808080|0, 0x2d8da1ac|0, 0x1fcfd3dc|0,
  0x2181a1a0|0, 0x30003030|0, 0x37073334|0, 0x2e8ea2ac|0, 0x36063234|0, 0x15051114|0, 0x22022220|0, 0x38083038|0,
  0x34c4f0f4|0, 0x2787a3a4|0, 0x05454144|0, 0x0c4c404c|0, 0x01818180|0, 0x29c9e1e8|0, 0x04848084|0, 0x17879394|0,
  0x35053134|0, 0x0bcbc3c8|0, 0x0ecec2cc|0, 0x3c0c303c|0, 0x31417170|0, 0x11011110|0, 0x07c7c3c4|0, 0x09898188|0,
  0x35457174|0, 0x3bcbf3f8|0, 0x1acad2d8|0, 0x38c8f0f8|0, 0x14849094|0, 0x19495158|0, 0x02828280|0, 0x04c4c0c4|0,
  0x3fcff3fc|0, 0x09494148|0, 0x39093138|0, 0x27476364|0, 0x00c0c0c0|0, 0x0fcfc3cc|0, 0x17c7d3d4|0, 0x3888b0b8|0,
  0x0f0f030c|0, 0x0e8e828c|0, 0x02424240|0, 0x23032320|0, 0x11819190|0, 0x2c4c606c|0, 0x1bcbd3d8|0, 0x2484a0a4|0,
  0x34043034|0, 0x31c1f1f0|0, 0x08484048|0, 0x02c2c2c0|0, 0x2f4f636c|0, 0x3d0d313c|0, 0x2d0d212c|0, 0x00404040|0,
  0x3e8eb2bc|0, 0x3e0e323c|0, 0x3c8cb0bc|0, 0x01c1c1c0|0, 0x2a8aa2a8|0, 0x3a8ab2b8|0, 0x0e4e424c|0, 0x15455154|0,
  0x3b0b3338|0, 0x1cccd0dc|0, 0x28486068|0, 0x3f4f737c|0, 0x1c8c909c|0, 0x18c8d0d8|0, 0x0a4a4248|0, 0x16465254|0,
  0x37477374|0, 0x2080a0a0|0, 0x2dcde1ec|0, 0x06464244|0, 0x3585b1b4|0, 0x2b0b2328|0, 0x25456164|0, 0x3acaf2f8|0,
  0x23c3e3e0|0, 0x3989b1b8|0, 0x3181b1b0|0, 0x1f8f939c|0, 0x1e4e525c|0, 0x39c9f1f8|0, 0x26c6e2e4|0, 0x3282b2b0|0,
  0x31013130|0, 0x2acae2e8|0, 0x2d4d616c|0, 0x1f4f535c|0, 0x24c4e0e4|0, 0x30c0f0f0|0, 0x0dcdc1cc|0, 0x08888088|0,
  0x16061214|0, 0x3a0a3238|0, 0x18485058|0, 0x14c4d0d4|0, 0x22426260|0, 0x29092128|0, 0x07070304|0, 0x33033330|0,
  0x28c8e0e8|0, 0x1b0b1318|0, 0x05050104|0, 0x39497178|0, 0x10809090|0, 0x2a4a6268|0, 0x2a0a2228|0, 0x1a8a9298|0,
]);

const SS1 = new Int32Array([
  0x38380830|0, 0xe828c8e0|0, 0x2c2d0d21|0, 0xa42686a2|0, 0xcc0fcfc3|0, 0xdc1eced2|0, 0xb03383b3|0, 0xb83888b0|0,
  0xac2f8fa3|0, 0x60204060|0, 0x54154551|0, 0xc407c7c3|0, 0x44044440|0, 0x6c2f4f63|0, 0x682b4b63|0, 0x581b4b53|0,
  0xc003c3c3|0, 0x60224262|0, 0x30330333|0, 0xb43585b1|0, 0x28290921|0, 0xa02080a0|0, 0xe022c2e2|0, 0xa42787a3|0,
  0xd013c3d3|0, 0x90118191|0, 0x10110111|0, 0x04060602|0, 0x1c1c0c10|0, 0xbc3c8cb0|0, 0x34360632|0, 0x480b4b43|0,
  0xec2fcfe3|0, 0x88088880|0, 0x6c2c4c60|0, 0xa82888a0|0, 0x14170713|0, 0xc404c4c0|0, 0x14160612|0, 0xf434c4f0|0,
  0xc002c2c2|0, 0x44054541|0, 0xe021c1e1|0, 0xd416c6d2|0, 0x3c3f0f33|0, 0x3c3d0d31|0, 0x8c0e8e82|0, 0x98188890|0,
  0x28280820|0, 0x4c0e4e42|0, 0xf436c6f2|0, 0x3c3e0e32|0, 0xa42585a1|0, 0xf839c9f1|0, 0x0c0d0d01|0, 0xdc1fcfd3|0,
  0xd818c8d0|0, 0x282b0b23|0, 0x64264662|0, 0x783a4a72|0, 0x24270723|0, 0x2c2f0f23|0, 0xf031c1f1|0, 0x70324272|0,
  0x40024242|0, 0xd414c4d0|0, 0x40014141|0, 0xc000c0c0|0, 0x70334373|0, 0x64274763|0, 0xac2c8ca0|0, 0x880b8b83|0,
  0xf437c7f3|0, 0xac2d8da1|0, 0x80008080|0, 0x1c1f0f13|0, 0xc80acac2|0, 0x2c2c0c20|0, 0xa82a8aa2|0, 0x34340430|0,
  0xd012c2d2|0, 0x080b0b03|0, 0xec2ecee2|0, 0xe829c9e1|0, 0x5c1d4d51|0, 0x94148490|0, 0x18180810|0, 0xf838c8f0|0,
  0x54174753|0, 0xac2e8ea2|0, 0x08080800|0, 0xc405c5c1|0, 0x10130313|0, 0xcc0dcdc1|0, 0x84068682|0, 0xb83989b1|0,
  0xfc3fcff3|0, 0x7c3d4d71|0, 0xc001c1c1|0, 0x30310131|0, 0xf435c5f1|0, 0x880a8a82|0, 0x682a4a62|0, 0xb03181b1|0,
  0xd011c1d1|0, 0x20200020|0, 0xd417c7d3|0, 0x00020202|0, 0x20220222|0, 0x04040400|0, 0x68284860|0, 0x70314171|0,
  0x04070703|0, 0xd81bcbd3|0, 0x9c1d8d91|0, 0x98198991|0, 0x60214161|0, 0xbc3e8eb2|0, 0xe426c6e2|0, 0x58194951|0,
  0xdc1dcdd1|0, 0x50114151|0, 0x90108090|0, 0xdc1cccd0|0, 0x981a8a92|0, 0xa02383a3|0, 0xa82b8ba3|0, 0xd010c0d0|0,
  0x80018181|0, 0x0c0f0f03|0, 0x44074743|0, 0x181a0a12|0, 0xe023c3e3|0, 0xec2ccce0|0, 0x8c0d8d81|0, 0xbc3f8fb3|0,
  0x94168692|0, 0x783b4b73|0, 0x5c1c4c50|0, 0xa02282a2|0, 0xa02181a1|0, 0x60234363|0, 0x20230323|0, 0x4c0d4d41|0,
  0xc808c8c0|0, 0x9c1e8e92|0, 0x9c1c8c90|0, 0x383a0a32|0, 0x0c0c0c00|0, 0x2c2e0e22|0, 0xb83a8ab2|0, 0x6c2e4e62|0,
  0x9c1f8f93|0, 0x581a4a52|0, 0xf032c2f2|0, 0x90128292|0, 0xf033c3f3|0, 0x48094941|0, 0x78384870|0, 0xcc0cccc0|0,
  0x14150511|0, 0xf83bcbf3|0, 0x70304070|0, 0x74354571|0, 0x7c3f4f73|0, 0x34350531|0, 0x10100010|0, 0x00030303|0,
  0x64244460|0, 0x6c2d4d61|0, 0xc406c6c2|0, 0x74344470|0, 0xd415c5d1|0, 0xb43484b0|0, 0xe82acae2|0, 0x08090901|0,
  0x74364672|0, 0x18190911|0, 0xfc3ecef2|0, 0x40004040|0, 0x10120212|0, 0xe020c0e0|0, 0xbc3d8db1|0, 0x04050501|0,
  0xf83acaf2|0, 0x00010101|0, 0xf030c0f0|0, 0x282a0a22|0, 0x5c1e4e52|0, 0xa82989a1|0, 0x54164652|0, 0x40034343|0,
  0x84058581|0, 0x14140410|0, 0x88098981|0, 0x981b8b93|0, 0xb03080b0|0, 0xe425c5e1|0, 0x48084840|0, 0x78394971|0,
  0x94178793|0, 0xfc3cccf0|0, 0x1c1e0e12|0, 0x80028282|0, 0x20210121|0, 0x8c0c8c80|0, 0x181b0b13|0, 0x5c1f4f53|0,
  0x74374773|0, 0x54144450|0, 0xb03282b2|0, 0x1c1d0d11|0, 0x24250521|0, 0x4c0f4f43|0, 0x00000000|0, 0x44064642|0,
  0xec2dcde1|0, 0x58184850|0, 0x50124252|0, 0xe82bcbe3|0, 0x7c3e4e72|0, 0xd81acad2|0, 0xc809c9c1|0, 0xfc3dcdf1|0,
  0x30300030|0, 0x94158591|0, 0x64254561|0, 0x3c3c0c30|0, 0xb43686b2|0, 0xe424c4e0|0, 0xb83b8bb3|0, 0x7c3c4c70|0,
  0x0c0e0e02|0, 0x50104050|0, 0x38390931|0, 0x24260622|0, 0x30320232|0, 0x84048480|0, 0x68294961|0, 0x90138393|0,
  0x34370733|0, 0xe427c7e3|0, 0x24240420|0, 0xa42484a0|0, 0xc80bcbc3|0, 0x50134353|0, 0x080a0a02|0, 0x84078783|0,
  0xd819c9d1|0, 0x4c0c4c40|0, 0x80038383|0, 0x8c0f8f83|0, 0xcc0ecec2|0, 0x383b0b33|0, 0x480a4a42|0, 0xb43787b3|0,
]);

const SS2 = new Int32Array([
  0xa1a82989|0, 0x81840585|0, 0xd2d416c6|0, 0xd3d013c3|0, 0x50541444|0, 0x111c1d0d|0, 0xa0ac2c8c|0, 0x21242505|0,
  0x515c1d4d|0, 0x43400343|0, 0x10181808|0, 0x121c1e0e|0, 0x51501141|0, 0xf0fc3ccc|0, 0xc2c80aca|0, 0x63602343|0,
  0x20282808|0, 0x40440444|0, 0x20202000|0, 0x919c1d8d|0, 0xe0e020c0|0, 0xe2e022c2|0, 0xc0c808c8|0, 0x13141707|0,
  0xa1a42585|0, 0x838c0f8f|0, 0x03000303|0, 0x73783b4b|0, 0xb3b83b8b|0, 0x13101303|0, 0xd2d012c2|0, 0xe2ec2ece|0,
  0x70703040|0, 0x808c0c8c|0, 0x333c3f0f|0, 0xa0a82888|0, 0x32303202|0, 0xd1dc1dcd|0, 0xf2f436c6|0, 0x70743444|0,
  0xe0ec2ccc|0, 0x91941585|0, 0x03080b0b|0, 0x53541747|0, 0x505c1c4c|0, 0x53581b4b|0, 0xb1bc3d8d|0, 0x01000101|0,
  0x20242404|0, 0x101c1c0c|0, 0x73703343|0, 0x90981888|0, 0x10101000|0, 0xc0cc0ccc|0, 0xf2f032c2|0, 0xd1d819c9|0,
  0x202c2c0c|0, 0xe3e427c7|0, 0x72703242|0, 0x83800383|0, 0x93981b8b|0, 0xd1d011c1|0, 0x82840686|0, 0xc1c809c9|0,
  0x60602040|0, 0x50501040|0, 0xa3a02383|0, 0xe3e82bcb|0, 0x010c0d0d|0, 0xb2b43686|0, 0x929c1e8e|0, 0x434c0f4f|0,
  0xb3b43787|0, 0x52581a4a|0, 0xc2c406c6|0, 0x70783848|0, 0xa2a42686|0, 0x12101202|0, 0xa3ac2f8f|0, 0xd1d415c5|0,
  0x61602141|0, 0xc3c003c3|0, 0xb0b43484|0, 0x41400141|0, 0x52501242|0, 0x717c3d4d|0, 0x818c0d8d|0, 0x00080808|0,
  0x131c1f0f|0, 0x91981989|0, 0x00000000|0, 0x11181909|0, 0x00040404|0, 0x53501343|0, 0xf3f437c7|0, 0xe1e021c1|0,
  0xf1fc3dcd|0, 0x72743646|0, 0x232c2f0f|0, 0x23242707|0, 0xb0b03080|0, 0x83880b8b|0, 0x020c0e0e|0, 0xa3a82b8b|0,
  0xa2a02282|0, 0x626c2e4e|0, 0x93901383|0, 0x414c0d4d|0, 0x61682949|0, 0x707c3c4c|0, 0x01080909|0, 0x02080a0a|0,
  0xb3bc3f8f|0, 0xe3ec2fcf|0, 0xf3f033c3|0, 0xc1c405c5|0, 0x83840787|0, 0x10141404|0, 0xf2fc3ece|0, 0x60642444|0,
  0xd2dc1ece|0, 0x222c2e0e|0, 0x43480b4b|0, 0x12181a0a|0, 0x02040606|0, 0x21202101|0, 0x63682b4b|0, 0x62642646|0,
  0x02000202|0, 0xf1f435c5|0, 0x92901282|0, 0x82880a8a|0, 0x000c0c0c|0, 0xb3b03383|0, 0x727c3e4e|0, 0xd0d010c0|0,
  0x72783a4a|0, 0x43440747|0, 0x92941686|0, 0xe1e425c5|0, 0x22242606|0, 0x80800080|0, 0xa1ac2d8d|0, 0xd3dc1fcf|0,
  0xa1a02181|0, 0x30303000|0, 0x33343707|0, 0xa2ac2e8e|0, 0x32343606|0, 0x11141505|0, 0x22202202|0, 0x30383808|0,
  0xf0f434c4|0, 0xa3a42787|0, 0x41440545|0, 0x404c0c4c|0, 0x81800181|0, 0xe1e829c9|0, 0x80840484|0, 0x93941787|0,
  0x31343505|0, 0xc3c80bcb|0, 0xc2cc0ece|0, 0x303c3c0c|0, 0x71703141|0, 0x11101101|0, 0xc3c407c7|0, 0x81880989|0,
  0x71743545|0, 0xf3f83bcb|0, 0xd2d81aca|0, 0xf0f838c8|0, 0x90941484|0, 0x51581949|0, 0x82800282|0, 0xc0c404c4|0,
  0xf3fc3fcf|0, 0x41480949|0, 0x31383909|0, 0x63642747|0, 0xc0c000c0|0, 0xc3cc0fcf|0, 0xd3d417c7|0, 0xb0b83888|0,
  0x030c0f0f|0, 0x828c0e8e|0, 0x42400242|0, 0x23202303|0, 0x91901181|0, 0x606c2c4c|0, 0xd3d81bcb|0, 0xa0a42484|0,
  0x30343404|0, 0xf1f031c1|0, 0x40480848|0, 0xc2c002c2|0, 0x636c2f4f|0, 0x313c3d0d|0, 0x212c2d0d|0, 0x40400040|0,
  0xb2bc3e8e|0, 0x323c3e0e|0, 0xb0bc3c8c|0, 0xc1c001c1|0, 0xa2a82a8a|0, 0xb2b83a8a|0, 0x424c0e4e|0, 0x51541545|0,
  0x33383b0b|0, 0xd0dc1ccc|0, 0x60682848|0, 0x737c3f4f|0, 0x909c1c8c|0, 0xd0d818c8|0, 0x42480a4a|0, 0x52541646|0,
  0x73743747|0, 0xa0a02080|0, 0xe1ec2dcd|0, 0x42440646|0, 0xb1b43585|0, 0x23282b0b|0, 0x61642545|0, 0xf2f83aca|0,
  0xe3e023c3|0, 0xb1b83989|0, 0xb1b03181|0, 0x939c1f8f|0, 0x525c1e4e|0, 0xf1f839c9|0, 0xe2e426c6|0, 0xb2b03282|0,
  0x31303101|0, 0xe2e82aca|0, 0x616c2d4d|0, 0x535c1f4f|0, 0xe0e424c4|0, 0xf0f030c0|0, 0xc1cc0dcd|0, 0x80880888|0,
  0x12141606|0, 0x32383a0a|0, 0x50581848|0, 0xd0d414c4|0, 0x62602242|0, 0x21282909|0, 0x03040707|0, 0x33303303|0,
  0xe0e828c8|0, 0x13181b0b|0, 0x01040505|0, 0x71783949|0, 0x90901080|0, 0x62682a4a|0, 0x22282a0a|0, 0x92981a8a|0,
]);

const SS3 = new Int32Array([
  0x08303838|0, 0xc8e0e828|0, 0x0d212c2d|0, 0x86a2a426|0, 0xcfc3cc0f|0, 0xced2dc1e|0, 0x83b3b033|0, 0x88b0b838|0,
  0x8fa3ac2f|0, 0x40606020|0, 0x45515415|0, 0xc7c3c407|0, 0x44404404|0, 0x4f636c2f|0, 0x4b63682b|0, 0x4b53581b|0,
  0xc3c3c003|0, 0x42626022|0, 0x03333033|0, 0x85b1b435|0, 0x09212829|0, 0x80a0a020|0, 0xc2e2e022|0, 0x87a3a427|0,
  0xc3d3d013|0, 0x81919011|0, 0x01111011|0, 0x06020406|0, 0x0c101c1c|0, 0x8cb0bc3c|0, 0x06323436|0, 0x4b43480b|0,
  0xcfe3ec2f|0, 0x88808808|0, 0x4c606c2c|0, 0x88a0a828|0, 0x07131417|0, 0xc4c0c404|0, 0x06121416|0, 0xc4f0f434|0,
  0xc2c2c002|0, 0x45414405|0, 0xc1e1e021|0, 0xc6d2d416|0, 0x0f333c3f|0, 0x0d313c3d|0, 0x8e828c0e|0, 0x88909818|0,
  0x08202828|0, 0x4e424c0e|0, 0xc6f2f436|0, 0x0e323c3e|0, 0x85a1a425|0, 0xc9f1f839|0, 0x0d010c0d|0, 0xcfd3dc1f|0,
  0xc8d0d818|0, 0x0b23282b|0, 0x46626426|0, 0x4a72783a|0, 0x07232427|0, 0x0f232c2f|0, 0xc1f1f031|0, 0x42727032|0,
  0x42424002|0, 0xc4d0d414|0, 0x41414001|0, 0xc0c0c000|0, 0x43737033|0, 0x47636427|0, 0x8ca0ac2c|0, 0x8b83880b|0,
  0xc7f3f437|0, 0x8da1ac2d|0, 0x80808000|0, 0x0f131c1f|0, 0xcac2c80a|0, 0x0c202c2c|0, 0x8aa2a82a|0, 0x04303434|0,
  0xc2d2d012|0, 0x0b03080b|0, 0xcee2ec2e|0, 0xc9e1e829|0, 0x4d515c1d|0, 0x84909414|0, 0x08101818|0, 0xc8f0f838|0,
  0x47535417|0, 0x8ea2ac2e|0, 0x08000808|0, 0xc5c1c405|0, 0x03131013|0, 0xcdc1cc0d|0, 0x86828406|0, 0x89b1b839|0,
  0xcff3fc3f|0, 0x4d717c3d|0, 0xc1c1c001|0, 0x01313031|0, 0xc5f1f435|0, 0x8a82880a|0, 0x4a62682a|0, 0x81b1b031|0,
  0xc1d1d011|0, 0x00202020|0, 0xc7d3d417|0, 0x02020002|0, 0x02222022|0, 0x04000404|0, 0x48606828|0, 0x41717031|0,
  0x07030407|0, 0xcbd3d81b|0, 0x8d919c1d|0, 0x89919819|0, 0x41616021|0, 0x8eb2bc3e|0, 0xc6e2e426|0, 0x49515819|0,
  0xcdd1dc1d|0, 0x41515011|0, 0x80909010|0, 0xccd0dc1c|0, 0x8a92981a|0, 0x83a3a023|0, 0x8ba3a82b|0, 0xc0d0d010|0,
  0x81818001|0, 0x0f030c0f|0, 0x47434407|0, 0x0a12181a|0, 0xc3e3e023|0, 0xcce0ec2c|0, 0x8d818c0d|0, 0x8fb3bc3f|0,
  0x86929416|0, 0x4b73783b|0, 0x4c505c1c|0, 0x82a2a022|0, 0x81a1a021|0, 0x43636023|0, 0x03232023|0, 0x4d414c0d|0,
  0xc8c0c808|0, 0x8e929c1e|0, 0x8c909c1c|0, 0x0a32383a|0, 0x0c000c0c|0, 0x0e222c2e|0, 0x8ab2b83a|0, 0x4e626c2e|0,
  0x8f939c1f|0, 0x4a52581a|0, 0xc2f2f032|0, 0x82929012|0, 0xc3f3f033|0, 0x49414809|0, 0x48707838|0, 0xccc0cc0c|0,
  0x05111415|0, 0xcbf3f83b|0, 0x40707030|0, 0x45717435|0, 0x4f737c3f|0, 0x05313435|0, 0x00101010|0, 0x03030003|0,
  0x44606424|0, 0x4d616c2d|0, 0xc6c2c406|0, 0x44707434|0, 0xc5d1d415|0, 0x84b0b434|0, 0xcae2e82a|0, 0x09010809|0,
  0x46727436|0, 0x09111819|0, 0xcef2fc3e|0, 0x40404000|0, 0x02121012|0, 0xc0e0e020|0, 0x8db1bc3d|0, 0x05010405|0,
  0xcaf2f83a|0, 0x01010001|0, 0xc0f0f030|0, 0x0a22282a|0, 0x4e525c1e|0, 0x89a1a829|0, 0x46525416|0, 0x43434003|0,
  0x85818405|0, 0x04101414|0, 0x89818809|0, 0x8b93981b|0, 0x80b0b030|0, 0xc5e1e425|0, 0x48404808|0, 0x49717839|0,
  0x87939417|0, 0xccf0fc3c|0, 0x0e121c1e|0, 0x82828002|0, 0x01212021|0, 0x8c808c0c|0, 0x0b13181b|0, 0x4f535c1f|0,
  0x47737437|0, 0x44505414|0, 0x82b2b032|0, 0x0d111c1d|0, 0x05212425|0, 0x4f434c0f|0, 0x00000000|0, 0x46424406|0,
  0xcde1ec2d|0, 0x48505818|0, 0x42525012|0, 0xcbe3e82b|0, 0x4e727c3e|0, 0xcad2d81a|0, 0xc9c1c809|0, 0xcdf1fc3d|0,
  0x00303030|0, 0x85919415|0, 0x45616425|0, 0x0c303c3c|0, 0x86b2b436|0, 0xc4e0e424|0, 0x8bb3b83b|0, 0x4c707c3c|0,
  0x0e020c0e|0, 0x40505010|0, 0x09313839|0, 0x06222426|0, 0x02323032|0, 0x84808404|0, 0x49616829|0, 0x83939013|0,
  0x07333437|0, 0xc7e3e427|0, 0x04202424|0, 0x84a0a424|0, 0xcbc3c80b|0, 0x43535013|0, 0x0a02080a|0, 0x87838407|0,
  0xc9d1d819|0, 0x4c404c0c|0, 0x83838003|0, 0x8f838c0f|0, 0xcec2cc0e|0, 0x0b33383b|0, 0x4a42480a|0, 0x87b3b437|0,
]);

const KC = new Int32Array([
  0x9e3779b9|0, 0x3c6ef373|0, 0x78dde6e6|0, 0xf1bbcdcc|0, 0xe3779b99|0, 0xc6ef3733|0, 0x8dde6e67|0, 0x1bbcdccf|0,
  0x3779b99e|0, 0x6ef3733c|0, 0xdde6e678|0, 0xbbcdccf1|0, 0x779b99e3|0, 0xef3733c6|0, 0xde6e678d|0, 0xbcdccf1b|0,
]);

const NO_ROUND_KEYS = 32;
const BLOCK = 16;

const b0 = (a) => a & 0xff;
const b1 = (a) => (a >>> 8) & 0xff;
const b2 = (a) => (a >>> 16) & 0xff;
const b3 = (a) => (a >>> 24) & 0xff;

const G = (x) => (SS0[b0(x)] ^ SS1[b1(x)] ^ SS2[b2(x)] ^ SS3[b3(x)]) | 0;

/**
 * The Java source widens to `long` before adding, then truncates back to `int`.
 * In JS, `(a + b) | 0` reproduces that exactly for 32-bit operands, since the
 * intermediate sum stays well inside the 2^53 safe-integer range.
 */
const add32 = (a, b) => (a + b) | 0;
const sub32 = (a, b) => (a - b) | 0;

/** F-function + Feistel XOR. Mutates the two left-hand words. */
function seedRound(L, R, k0, k1) {
  let t0 = (R[0] ^ k0) | 0;
  let t1 = (R[1] ^ k1) | 0;
  t1 = (t1 ^ t0) | 0;

  t1 = G(t1);
  t0 = add32(t0, t1);
  t0 = G(t0);
  t1 = add32(t1, t0);
  t1 = G(t1);
  t0 = add32(t0, t1);

  L[0] = (L[0] ^ t0) | 0;
  L[1] = (L[1] ^ t1) | 0;
}

/** Big-endian 4 bytes -> int32, matching the Java shift-and-or loop. */
function beWord(bytes, off) {
  return (
    ((bytes[off] & 0xff) << 24) |
    ((bytes[off + 1] & 0xff) << 16) |
    ((bytes[off + 2] & 0xff) << 8) |
    (bytes[off + 3] & 0xff)
  ) | 0;
}

function putWord(out, off, word) {
  out[off] = (word >>> 24) & 0xff;
  out[off + 1] = (word >>> 16) & 0xff;
  out[off + 2] = (word >>> 8) & 0xff;
  out[off + 3] = word & 0xff;
}

/** Key schedule — 32 round-key words from a 16-byte user key. */
export function seedRoundKey(userKey) {
  if (userKey.length !== BLOCK) {
    throw new Error(`SEED key must be exactly 16 bytes, got ${userKey.length}`);
  }

  const rk = new Int32Array(NO_ROUND_KEYS);
  let A = beWord(userKey, 0);
  let B = beWord(userKey, 4);
  let C = beWord(userKey, 8);
  let D = beWord(userKey, 12);

  let n = 0;
  let t0 = sub32(add32(A, C), KC[0]);
  let t1 = add32(sub32(B, D), KC[0]);
  rk[n++] = G(t0);
  rk[n++] = G(t1);

  // Alternates update0 (rotate A,B right by 8) and update1 (rotate C,D left by 8).
  for (let z = 1; z <= 15; z++) {
    if (z % 2 === 1) {
      const tmp = A;
      A = ((A >>> 8) ^ (B << 24)) | 0;
      B = ((B >>> 8) ^ (tmp << 24)) | 0;
    } else {
      const tmp = C;
      C = ((C << 8) ^ (D >>> 24)) | 0;
      D = ((D << 8) ^ (tmp >>> 24)) | 0;
    }
    t0 = sub32(add32(A, C), KC[z]);
    t1 = sub32(add32(B, KC[z]), D);
    rk[n++] = G(t0);
    rk[n++] = G(t1);
  }

  return rk;
}

/** Encrypt exactly one 16-byte block. */
export function seedEncryptBlock(block, rk) {
  const L = [beWord(block, 0), beWord(block, 4)];
  const R = [beWord(block, 8), beWord(block, 12)];

  for (let i = 0; i < 16; i++) {
    const k0 = rk[i * 2];
    const k1 = rk[i * 2 + 1];
    if (i % 2 === 0) seedRound(L, R, k0, k1);
    else seedRound(R, L, k0, k1);
  }

  // Halves are swapped on output — this is the final-swap the Java code performs
  // by writing R first.
  const out = new Uint8Array(BLOCK);
  putWord(out, 0, R[0]);
  putWord(out, 4, R[1]);
  putWord(out, 8, L[0]);
  putWord(out, 12, L[1]);
  return out;
}

/** Decrypt exactly one 16-byte block — same network, round keys reversed pairwise. */
export function seedDecryptBlock(block, rk) {
  const L = [beWord(block, 0), beWord(block, 4)];
  const R = [beWord(block, 8), beWord(block, 12)];

  for (let i = 0; i < 16; i++) {
    const idx = 30 - i * 2;
    const k0 = rk[idx];
    const k1 = rk[idx + 1];
    if (i % 2 === 0) seedRound(L, R, k0, k1);
    else seedRound(R, L, k0, k1);
  }

  const out = new Uint8Array(BLOCK);
  putWord(out, 0, R[0]);
  putWord(out, 4, R[1]);
  putWord(out, 8, L[0]);
  putWord(out, 12, L[1]);
  return out;
}

/** Zero-pad to a whole number of blocks. Empty input still yields one block. */
function zeroPad(bytes) {
  const blocks = bytes.length === 0 ? 1 : Math.ceil(bytes.length / BLOCK);
  const out = new Uint8Array(blocks * BLOCK);
  out.set(bytes);
  return out;
}

const toHex = (bytes) => Buffer.from(bytes).toString('hex');
const fromHex = (hex) => Uint8Array.from(Buffer.from(hex, 'hex'));

/**
 * Encrypt a plaintext string to lowercase hex, matching SEED128.getEncryptData.
 *
 * @param {string} key      16-character 보안키 (used as raw bytes)
 * @param {string} plain    the "a=1&b=2" parameter string
 * @param {string} encoding character set for the plaintext; epost's newer
 *                          endpoints expect UTF-8
 */
export function encryptData(key, plain, encoding = 'utf8') {
  const keyBytes = Uint8Array.from(Buffer.from(key, 'binary'));
  const rk = seedRoundKey(keyBytes);
  const data = zeroPad(Uint8Array.from(Buffer.from(plain, encoding)));

  const out = new Uint8Array(data.length);
  for (let off = 0; off < data.length; off += BLOCK) {
    out.set(seedEncryptBlock(data.subarray(off, off + BLOCK), rk), off);
  }
  return toHex(out);
}

/** Inverse of encryptData. Trailing NUL padding is stripped. */
export function decryptData(key, hex, encoding = 'utf8') {
  const keyBytes = Uint8Array.from(Buffer.from(key, 'binary'));
  const rk = seedRoundKey(keyBytes);
  const data = zeroPad(fromHex(hex));

  const out = new Uint8Array(data.length);
  for (let off = 0; off < data.length; off += BLOCK) {
    out.set(seedDecryptBlock(data.subarray(off, off + BLOCK), rk), off);
  }

  let end = out.length;
  while (end > 0 && out[end - 1] === 0x00) end -= 1;
  return Buffer.from(out.subarray(0, end)).toString(encoding);
}
